#!/usr/bin/env node
/**
 * Generate a simplified static model list from pi-ai package.
 * Extracts only {provider, id, name} for each model to minimize payload size.
 */

import { readFileSync, writeFileSync } from 'fs';
import { resolve, join } from 'path';

const modelsGeneratedPath = resolve(join(process.cwd(), 'node_modules/@mariozechner/pi-ai/dist/models.generated.js'));

console.log('Loading models from:', modelsGeneratedPath);

const content = readFileSync(modelsGeneratedPath, 'utf-8');

// Extract the MODELS object using a simple regex approach
// The file format is: export const MODELS = { ... };
const match = content.match(/export\s+const\s+MODELS\s*=\s*(\{[\s\S]*\});?$/);

if (!match) {
    console.error('Failed to extract MODELS from file');
    process.exit(1);
}

// We need to evaluate the MODELS object safely
// Create a minimal sandbox to extract the data
const modelsModule = new Function(`
    const MODELS = ${match[1]};
    return MODELS;
`)();

const simplifiedModels = [];

for (const [provider, models] of Object.entries(modelsModule)) {
    for (const [id, model] of Object.entries(models)) {
        simplifiedModels.push({
            provider: model.provider || provider,
            id: model.id || id,
            name: model.name || id,
        });
    }
}

// Sort by provider then name
simplifiedModels.sort((a, b) => {
    if (a.provider !== b.provider) return a.provider.localeCompare(b.provider);
    return a.name.localeCompare(b.name);
});

const outputPath = resolve(join(process.cwd(), 'src-tauri/src/models_static.rs'));
writeFileSync(outputPath, `// Auto-generated by scripts/generate-static-models.ts
// Do not edit manually

use serde::Serialize;

#[derive(Debug, Clone, Serialize)]
pub struct StaticModel {
    pub provider: &'static str,
    pub id: &'static str,
    pub name: &'static str,
}

pub fn get_static_models() -> &'static [StaticModel] {
    &[
${
    simplifiedModels.map(m => `        StaticModel {
            provider: "${m.provider}",
            id: "${m.id}",
            name: "${m.name}",
        },`).join('\n')
    }
    ]
}
`);

console.log(`Generated ${simplifiedModels.length} models to ${outputPath}`);
console.log(`Output file size: ${(outputPath.length / 1024).toFixed(2)} KB`);
